# Generated by Django 5.2.3 on 2025-06-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventAppInside', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassThrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_event', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('timestamp', models.DateField()),
                ('photo_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_name', models.CharField(max_length=255)),
                ('image_data', models.BinaryField()),
            ],
        ),
    ]
