# Generated by Django 5.2.3 on 2025-06-23 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventAppInside', '0002_passthrough_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo_store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.BinaryField()),
                ('photo_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('event_type', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='PassThrough',
        ),
        migrations.AlterField(
            model_name='registration',
            name='user_name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
