# Generated by Django 5.2.3 on 2025-06-23 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventAppInside', '0003_photo_store_delete_passthrough_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo_store',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='photo_store',
            name='photo_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
